In [87]:
import argparse
import json
import h5py
import imageio
import numpy as np
import os
from copy import deepcopy
import glob 

import torch

import robomimic
import robomimic.utils.file_utils as FileUtils
import robomimic.utils.torch_utils as TorchUtils
import robomimic.utils.tensor_utils as TensorUtils
import robomimic.utils.obs_utils as ObsUtils
from robomimic.envs.env_base import EnvBase
from robomimic.algo import RolloutPolicy

In [88]:
import pandas as pd
import numpy as np

csv_folder = "/home/sj/assistive_feed_gello/Assistive_Feeding_Gello/csv/samestartgoal200/test"
end_eff_folder = "/home/sj/assistive_feed_gello/Assistive_Feeding_Gello/csv/samestartdiffgoalsp100/end_eff5/test"

csv_files = glob.glob(os.path.join(csv_folder, '*.csv'))
end_eff_files = glob.glob(os.path.join(end_eff_folder, '*.csv'))

low_dim_data = []

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

for csv_file, end_eff_file in zip(csv_files, end_eff_files):
        joint_data = pd.read_csv(csv_file, usecols=range(0, 6), engine='python').astype(np.float64)
        end_eff_pos_data = pd.read_csv(end_eff_file, usecols=range(0, 3), engine='python').astype(np.float64)
        end_eff_quat_data = pd.read_csv(end_eff_file, usecols=range(3, 7), engine='python').astype(np.float64)

        joint_data = torch.tensor(joint_data.values).float().to(device)
        end_eff_pos_data = torch.tensor(end_eff_pos_data.values).float().to(device)
        end_eff_quat_data = torch.tensor(end_eff_quat_data.values).float().to(device)

# obs = {"robot0_joint_pos": joint_data, "robot0_eef_pos": end_eff_pos_data, "robot0_eef_quat": end_eff_quat_data}
# print(obs["robot0_joint_pos"].shape, obs["robot0_eef_pos"].shape, obs["robot0_eef_quat"].shape)

obs = {"robot0_joint_pos": joint_data}
print(obs["robot0_joint_pos"].shape)

torch.Size([77, 6])


In [89]:
# ckpt_path = "/home/sj/assistive_feed_gello/Assistive_Feeding_Gello/robomimic/bc_trained_models/allready2/20240607064247/models/model_epoch_100.pth"
ckpt_path = "/home/sj/assistive_feed_gello/Assistive_Feeding_Gello/robomimic/bc_trained_models/allready3/20240608182338/models/model_epoch_50.pth"
# Restore policy
policy, ckpt_dict = FileUtils.policy_from_checkpoint(ckpt_path=ckpt_path, device=device, verbose=True)


============= Loaded Config =============
{
    "algo_name": "bc",
    "experiment": {
        "name": "allready3",
        "validate": false,
        "logging": {
            "terminal_output_to_txt": true,
            "log_tb": true,
            "log_wandb": false,
            "wandb_proj_name": "debug"
        },
        "save": {
            "enabled": true,
            "every_n_seconds": null,
            "every_n_epochs": 50,
            "epochs": [],
            "on_best_validation": false,
            "on_best_rollout_return": false,
            "on_best_rollout_success_rate": true
        },
        "epoch_every_n_steps": 100,
        "validation_epoch_every_n_steps": 10,
        "env": null,
        "additional_envs": null,
        "render": false,
        "render_video": false,
        "keep_all_videos": false,
        "video_skip": 5,
        "rollout": {
            "enabled": false,
            "n": 50,
            "horizon": 400,
            "rate": 50,
            "warm

In [92]:
for i in range(len(obs["robot0_joint_pos"])):
    obs_to_pass = {"robot0_joint_pos": obs["robot0_joint_pos"][i]}
    print(obs_to_pass["robot0_joint_pos"])
    action = policy(obs_to_pass)
    print(action)

tensor([-1.4682, -1.4854, -1.6127, -1.5754,  1.5409,  1.4728])
here
obs robot0_joint_pos torch.Size([1, 1, 6])
[6]
[-0.9999885 -1.        -1.        -1.         1.         1.       ]
tensor([-1.4648, -1.4907, -1.6025, -1.5751,  1.5414,  1.4726])
here
obs robot0_joint_pos torch.Size([1, 1, 6])
[6]
[-1. -1. -1. -1.  1.  1.]
tensor([-1.4639, -1.4926, -1.6030, -1.5753,  1.5416,  1.4726])
here
obs robot0_joint_pos torch.Size([1, 1, 6])
[6]
[-1. -1. -1. -1.  1.  1.]
tensor([-1.4635, -1.4945, -1.6012, -1.5754,  1.5417,  1.4726])
here
obs robot0_joint_pos torch.Size([1, 1, 6])
[6]
[-1. -1. -1. -1.  1.  1.]
tensor([-1.4613, -1.4976, -1.5956, -1.5743,  1.5427,  1.4726])
here
obs robot0_joint_pos torch.Size([1, 1, 6])
[6]
[-1. -1. -1. -1.  1.  1.]
tensor([-1.4345, -1.4992, -1.5927, -1.5747,  1.5430,  1.4734])
here
obs robot0_joint_pos torch.Size([1, 1, 6])
[6]
[-1. -1. -1. -1.  1.  1.]
tensor([-1.4021, -1.5045, -1.5936, -1.5759,  1.5431,  1.4739])
here
obs robot0_joint_pos torch.Size([1, 1, 6])
[

In [77]:
for i in range(len(obs["robot0_joint_pos"])):
    obs_to_pass = {"robot0_joint_pos": obs["robot0_joint_pos"][i], "robot0_eef_pos": obs["robot0_eef_pos"][i], "robot0_eef_quat": obs["robot0_eef_quat"][i]}
    print(obs_to_pass["robot0_joint_pos"])
    action = policy(obs_to_pass)
    print(action)

tensor([-0.7689, -1.6343, -1.3877, -1.5442,  1.8756,  1.8521])
here
obs robot0_eef_pos torch.Size([1, 1, 3])
[3]
obs robot0_eef_quat torch.Size([1, 1, 4])
[4]
obs robot0_joint_pos torch.Size([1, 1, 6])
[6]
[-0.3798572 -1.        -1.        -1.         1.         1.       ]
tensor([-0.7343, -1.6726, -1.4090, -1.5050,  1.9257,  1.8537])
here
obs robot0_eef_pos torch.Size([1, 1, 3])
[3]
obs robot0_eef_quat torch.Size([1, 1, 4])
[4]
obs robot0_joint_pos torch.Size([1, 1, 6])
[6]
[-0.48469228 -1.         -1.         -1.          1.          1.        ]
tensor([-0.7173, -1.7146, -1.4494, -1.4275,  1.9504,  1.8526])
here
obs robot0_eef_pos torch.Size([1, 1, 3])
[3]
obs robot0_eef_quat torch.Size([1, 1, 4])
[4]
obs robot0_joint_pos torch.Size([1, 1, 6])
[6]
[-0.5485075 -1.        -1.        -1.         1.         1.       ]
tensor([-0.7026, -1.7786, -1.5010, -1.2984,  1.9566,  1.8535])
here
obs robot0_eef_pos torch.Size([1, 1, 3])
[3]
obs robot0_eef_quat torch.Size([1, 1, 4])
[4]
obs robot0_jo

In [91]:
def action_from_policy(policy, obs):
    # Get action from policy
    action = policy(obs)
    print(action)
    return action

for i in range(len(obs["robot0_joint_pos"])):
    if i==0:
        obs_to_pass = {"robot0_joint_pos": obs["robot0_joint_pos"]}
        print(obs_to_pass["robot0_joint_pos"])
        action = policy(obs_to_pass)
        print(action)
        continue
    print("i", i)
    obs_to_pass = {"robot0_joint_pos": action}
    print(obs_to_pass["robot0_joint_pos"])
    action = policy(obs_to_pass)
    print(action)

tensor([[-1.4682, -1.4854, -1.6127, -1.5754,  1.5409,  1.4728],
        [-1.4648, -1.4907, -1.6025, -1.5751,  1.5414,  1.4726],
        [-1.4639, -1.4926, -1.6030, -1.5753,  1.5416,  1.4726],
        [-1.4635, -1.4945, -1.6012, -1.5754,  1.5417,  1.4726],
        [-1.4613, -1.4976, -1.5956, -1.5743,  1.5427,  1.4726],
        [-1.4345, -1.4992, -1.5927, -1.5747,  1.5430,  1.4734],
        [-1.4021, -1.5045, -1.5936, -1.5759,  1.5431,  1.4739],
        [-1.3793, -1.5111, -1.5955, -1.5760,  1.5431,  1.4741],
        [-1.3318, -1.5263, -1.5941, -1.5756,  1.5424,  1.4734],
        [-1.2774, -1.5352, -1.5929, -1.5754,  1.5419,  1.4728],
        [-1.2342, -1.5377, -1.5917, -1.5754,  1.5410,  1.4727],
        [-1.1528, -1.5376, -1.5894, -1.5746,  1.5403,  1.4726],
        [-1.0683, -1.5365, -1.5874, -1.5741,  1.5394,  1.4733],
        [-1.0098, -1.5380, -1.5873, -1.5739,  1.5389,  1.4739],
        [-0.9384, -1.5622, -1.5794, -1.5732,  1.5387,  1.4741],
        [-0.8835, -1.5890, -1.5699, -1.5

AssertionError: 